In [139]:
import numpy as np

sector = np.array([[1,2], [3,2]])
print(sector)
val = np.array([[.5, .6],[.7, .8]])
ans = np.zeros((ind.shape))

diff_sectors = np.unique(sector)

for s in diff_sectors:
  find_s = (sector == s)  
  val_find = val*find_s
  sum_val = np.sum(val_find,axis=0)
  count_val = np.count_nonzero(val_find,axis=0)
  ans = ans + np.nan_to_num(sum_val/count_val * find_s)
ans

[[1 2]
 [3 2]]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:15: RuntimeWarning: invalid value encountered in true_divide
  from ipykernel import kernelapp as app


array([[0.5, 0.7],
       [0.7, 0.7]])

In [138]:
import numpy as np


ind = sector
ret = np.array([[0.5,0.6],[0.7,0.8]])

# print(ret[[0,1]][1])

# print(ret)

ans = np.zeros((ind.shape))

dic = {}
for i in range(ind.shape[1]):
#     print(i)
    l = np.array(ind[:][i])
#     print(ind[:][i])
#     print(l)
    distinct = np.unique(l)
#     print(distinct)
    for dis in distinct:
#         print(dis)
        d = np.array(np.where(l == dis))
        d = d.flatten()
        d = d.tolist()
#         print(d)
#         print(i)
        
        #######
#         print(ret[d,i]) ### This is not printing correctly
        ########
        
        lis = np.array(ret[d,i])
        print(lis)
        dic[dis] = sum(lis)/len(d)
        ans[d,i] = dic[dis]
        
#     ind = ind[]

ans


ans

[0.5]
[0.7]
[0.8]
[0.6]


array([[0.5, 0.6],
       [0.7, 0.8]])

In [113]:
import numpy as np

sector = np.array([[1,1],[2,2]])
print(sector)
val = np.array([[.5, .6],[.7, .8]])
ans = np.zeros((ind.shape))

diff_sectors = np.unique(sector)

for s in diff_sectors:
  find_s = (sector == s)  
  val_find = val*find_s

  print(val_find[val_find!=0])
  print(val_find[val_find.nonzero()].mean(axis = 0) * find_s)
  ans = ans + val_find.sum()/(val_find!=0).count()* find_s
ans

[[1 1]
 [2 2]]
[0.5 0.6]
[[0.55 0.55]
 [0.   0.  ]]


AttributeError: ignored